# Generated by Django 2.2.13 on 2020-07-01 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='note',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
